from collections.abc import Callable, Iterable, Sequence
from typing import Literal, NamedTuple, TypeAlias, overload

import cadquery as cq
from manifold3d import CrossSection, Manifold, Mesh

CQ_TESSELLATION_TOLERANCE: float

_Faces: TypeAlias = str | Iterable[str]
_Matrix: TypeAlias = Sequence[Sequence[float]]
_Point2D: TypeAlias = Sequence[float]
_Point3D: TypeAlias = Sequence[float]

class Size(NamedTuple):
    x: float
    y: float
    z: float

class Solid:
    manifold: Manifold

    def __init__(self, manifold: Manifold = ...) -> None: ...
    def __add__(self, other: Solid) -> Solid: ...
    def __sub__(self, other: Solid) -> Solid: ...
    def __and__(self, other: Solid) -> Solid: ...
    def as_original(self) -> Solid: ...
    def bounding_box(self) -> tuple[float, float, float, float, float, float]: ...
    def size(self) -> Size: ...
    def calculate_curvature(self, gaussian_idx: int, mean_idx: int) -> Solid: ...
    def align(
        self,
        xmin: float | None = ...,
        x: float | None = ...,
        xmax: float | None = ...,
        ymin: float | None = ...,
        y: float | None = ...,
        ymax: float | None = ...,
        zmin: float | None = ...,
        z: float | None = ...,
        zmax: float | None = ...,
    ) -> Solid: ...
    def align_to(
        self,
        other: Solid,
        faces: _Faces = ...,
        dx: float = ...,
        dy: float = ...,
        dz: float = ...,
    ) -> Solid: ...
    def decompose(self) -> list[Solid]: ...
    def genus(self) -> int: ...
    def get_surface_area(self) -> float: ...
    def get_volume(self) -> float: ...
    def hull(self, *others: Solid) -> Solid: ...
    def is_empty(self) -> bool: ...
    def mirror(self, x: float = ..., y: float = ..., z: float = ...) -> Solid: ...
    def num_edge(self) -> int: ...
    def num_prop(self) -> int: ...
    def num_prop_vert(self) -> int: ...
    def num_tri(self) -> int: ...
    def num_vert(self) -> int: ...
    def original_id(self) -> int: ...
    def precision(self) -> float: ...
    def refine(self, n: int = ...) -> Solid: ...
    def rotate(self, x: float = ..., y: float = ..., z: float = ...) -> Solid: ...
    def rotate_axis(self, axis: Literal["X", "Y", "Z"], degree: float) -> Solid: ...
    def scale(self, x: float = ..., y: float = ..., z: float = ...) -> Solid: ...
    def set_properties(self, *args: object, **kwargs: object) -> None: ...
    def split(self, cutter: Manifold) -> tuple[Solid, Solid]: ...
    def split_by_plane(
        self,
        x: float = ...,
        y: float = ...,
        z: float = ...,
        offset: float = ...,
    ) -> tuple[Solid, Solid]: ...
    def status(self) -> object: ...
    def to_mesh(self, normal_idx: int = ...) -> Mesh: ...
    def transform(self, matrix: _Matrix) -> Solid: ...
    def move(self, x: float = ..., y: float = ..., z: float = ...) -> Solid: ...
    def trim_by_plane(
        self,
        x: float = ...,
        y: float = ...,
        z: float = ...,
        offset: float = ...,
    ) -> Solid: ...
    def warp(self, xyz_map_fn: Callable[..., object]) -> Solid: ...
    def warp_batch(self, xyz_map_fn: Callable[..., object]) -> Solid: ...
    def refine_to_length(self, edge_len: float) -> Solid: ...
    @overload
    def stl(self, filename: None = ...) -> bytes: ...
    @overload
    def stl(self, filename: str) -> Solid: ...
    def to_cq(self) -> cq.Workplane: ...

class Shape:
    cross_section: CrossSection

    def __init__(self, cross_section: CrossSection = ...) -> None: ...
    def __add__(self, other: Shape) -> Shape: ...
    def __sub__(self, other: Shape) -> Shape: ...
    def __and__(self, other: Shape) -> Shape: ...
    def area(self) -> float: ...
    def bounds(self) -> tuple[float, float, float, float]: ...
    def align(
        self,
        xmin: float | None = ...,
        x: float | None = ...,
        xmax: float | None = ...,
        ymin: float | None = ...,
        y: float | None = ...,
        ymax: float | None = ...,
    ) -> Shape: ...
    def align_to(
        self,
        other: Shape,
        faces: _Faces = ...,
        dx: float = ...,
        dy: float = ...,
    ) -> Shape: ...
    def decompose(self) -> list[Shape]: ...
    def extrude(
        self,
        height: float,
        fn: int = ...,
        twist: float = ...,
        scale_top: tuple[float, float] = ...,
        center: bool = ...,
    ) -> Solid: ...
    def extrude_to(self, other: Shape, height: float, center: bool = ...) -> Solid: ...
    def refine_to_length(self, length: float) -> Shape: ...
    def hull(self, *others: Shape) -> Shape: ...
    def is_empty(self) -> bool: ...
    def mirror(self, x: float = ..., y: float = ...) -> Shape: ...
    def num_contour(self) -> int: ...
    def num_vert(self) -> int: ...
    def offset(
        self,
        delta: float,
        join_type: Literal["miter", "round", "square"] = ...,
        miter_limit: float = ...,
        circular_segments: int = ...,
    ) -> Shape: ...
    def revolve(self, z: float = ..., fn: int = ...) -> Solid: ...
    def rotate(self, z: float) -> Shape: ...
    def rotate_axis(self, axis: Literal["Z"], degree: float) -> Shape: ...
    def scale(self, x: float = ..., y: float = ...) -> Shape: ...
    def simplify(self, eps: float) -> Shape: ...
    def to_polygons(self) -> Sequence[Sequence[_Point2D]]: ...
    def transform(self, matrix: _Matrix) -> Shape: ...
    def move(self, x: float = ..., y: float = ...) -> Shape: ...
    def warp(self, xy_map_func: Callable[..., object]) -> Shape: ...
    def warp_batch(self, xy_map_func: Callable[..., object]) -> Shape: ...

def get_circular_segments(radius: float) -> int: ...
def set_circular_segments(nseg: int) -> None: ...
def set_min_circular_angle(degrees: float) -> None: ...
def set_min_circular_edge_length(length: float) -> None: ...
def hull(*solids: Solid) -> Solid: ...
def hull_points(points: Iterable[_Point3D]) -> Shape: ...
def hull2d(*shapes: Shape) -> Shape: ...
def hull2d_points(points: Iterable[_Point2D]) -> Shape: ...
def cube(
    x: float = ..., y: float = ..., z: float = ..., center: bool = ...
) -> Solid: ...
def box(
    x: float = ..., y: float = ..., z: float = ..., center: bool = ...
) -> Solid: ...
def cylinder(
    h: float = ...,
    d: float = ...,
    r: float | None = ...,
    r2: float | None = ...,
    center: bool = ...,
    fn: int = ...,
    outer: bool = ...,
) -> Solid: ...
def conic(
    h: float = ...,
    d1: float = ...,
    d2: float = ...,
    r1: float | None = ...,
    r2: float | None = ...,
    center: bool = ...,
    fn: int = ...,
    outer: bool = ...,
) -> Solid: ...
def sphere(d: float = ..., r: float | None = ..., fn: int = ...) -> Solid: ...
def circle(
    d: float = ...,
    r: float | None = ...,
    fn: int = ...,
    outer: bool = ...,
) -> Shape: ...
def square(x: float = ..., y: float = ..., center: bool = ...) -> Shape: ...
def polygon(
    points: Iterable[_Point2D],
    fill_rule: Literal["even_odd", "negative", "non_zero", "positive"] = ...,
    relative: bool = ...,
) -> Shape: ...
def cross_section(solid: Solid, z: float = ...) -> Shape: ...
def text(t: str, size: float = ..., font: str = ..., fn: int = ...) -> Shape: ...
def threads(
    d: float = ...,
    h: float = ...,
    pitch: float = ...,
    depth_ratio: float = ...,
    trap_scale: float = ...,
    starts: int = ...,
    fn: int = ...,
    pitch_fn: int = ...,
    lefty: bool = ...,
) -> Solid: ...
def load_stl(filename: str | None = ..., data: bytes | None = ...) -> Solid: ...
def to_cq(obj: Solid | Manifold) -> cq.Workplane: ...
def from_cq(obj: cq.Workplane, tolerance: float = ...) -> Solid: ...
